### ISSUE TITLE
Service /usr/bin/chromedriver unexpectedly exited

### ISSUE THREAD

**Issue by le-pet** [mdeweerd/MetersToHA#1]
all is in the title, i have any logs or more info is anonyoing, the error started after a update  via HACS.

here is the mesage:  Start the browser Message: Service /usr/bin/chromedriver unexpectedly exited. Status code was: 1

**Comment by mdeweerd** [comment]
I assume you are using AppDaemon.

Chromedriver is started by the script and you should get some kind of log before you get that error.

Regarding the logs - while writing this up, I notice that there are too many configurations to set where to log things, which has several reasons.

If you are using AppDaemon, then you can set the log folder explicitly with the option log_folder - this will set it to `/config`/
You can also set outfile and errfile.
```
  log_folder: /config
  # optional (Default: None) - Set file for stdout of script call
  outfile: /config/appdaemon/apps/testv2.log
  # optional (Default: None) - Set extra options for script call
  errfile: /config/appdaemon/apps/testv2err.log
```

Otherwise they will be in /config/appdaemon/apps/MetersToHA/ .

`service.log` is written to `/config/appdaemon/apps/MetersToHA/` unless you have set `logs_folder` in the json configuration.
`service.log` is the main log.

Regarding the logs you can have:
- service.log - located in the logs_folder set in the JSON file (by default `/config/appdaemon/apps/MetersToHA/` ) - this is output from the meters_to_ha.py script that is specifically written to that file - it shows the progress and result of each step;
- chromedriver.log - located in the logs_folder set in the appdaemon yaml configuration file (this is output from chromedriver - could help identify the reason for chromedriver exiting).
- The 'outfile' and 'errfile' as set in the appdaemon configuration (not written by default) - this is output from the python process (also from the meters_to_ha.py script, but would only contain unexpected output).


So normally you should have some logs that would help understand this.

**Comment by mdeweerd** [comment]
I am closing this:
- Lack of feedback;
- Several changes made for Chrome 110 compatibility.
