### ISSUE TITLE
Integrate a new captcha solving service

### ISSUE THREAD

**Issue by beropex** [mdeweerd/MetersToHA#7]
Hello, could you integrate capsolver.com? it's more cheap than other captcha solving services.

**Comment by mdeweerd** [comment]
I will not personnally integrate capsolver:
1. The API requires sending the image/question while the current solvers send some kind of key - so that requires extra work to implement and make sure that it works.
2. There are not that many users that would justify the "virtual cost" of adding capsolver to Meters2HA.

Also: did you check the minimum payment to add money to the account?  With the current solution the minimum payments already give 2.5 (2captcha) or 10 years of operation (capmonster).

I think capmonster has about the same cost as capsolver and it is faster.

I do accept any PR that integrates capsolver if somebody wants to code it.
