### ISSUE TITLE
Please add captchaai.com

### ISSUE THREAD

**Issue by sxdfgnb** [mdeweerd/MetersToHA#8]
Hi,

Can you please add support for Captchaai? Docs can be found here https://captchaai.com/api-docs.php

Thanks

**Comment by mdeweerd** [comment]
The method seems quite similar to the methods already implemented.

However, is it worthwhile to spend time on this.  The minimum plan is $15/month.

**Comment by mdeweerd** [comment]
Where can I see the offers <<$15/month ?

**Comment by sxdfgnb** [comment]
I found it [here ](https://www.blackhatworld.com/seo/captchaai-accurate-100-recaptcha-ocr-services-7-day-free-trial-for-bhw-users.1377255/)

But I think if you contact them You will get the same offer

**Comment by sxdfgnb** [comment]
Also, you can be part of the Referral Program if you looking to earn extra passive money

**Comment by mdeweerd** [comment]
Thank you for the link to the pricing (>=15$/month) and the free 7 day trial.  The [pricing on the company's site seems similar](https://captchaai.com/#pricing).

My point is that we currently have 2captcha (minimum $3 one-time, good for about 1000 captchas or 2.5 years of operation, human resolution) and capmonster (minimum $6 one time, good for about 10000 captchase or >= 25 years of operation, AI resolution).
Both these solutions cost way less than $15/month and one of them is AI based.

The (virtual) cost of my time to add this is around $150 and according to statistics there are less then 25 users.

I am not looking to gain money from this, but supposing that there are users preferring to pay $15/month for AI resolution, rather than $6 one time, and supposing that [referral is 10% of these sums](https://www.capsolver.com/#referral) and an ROI in 18 months, then 6 referrals paying a monthly $15 would pay back the effort.

Currently there are less then 25 users, and I do not see why anyone would choose to pay $15/month to get meter data of one meter, especially with the two low cost options available.

**Comment by sxdfgnb** [comment]
Hi 
I understand your Point of view but you miss this feature "Solve UNLIMITED Captchas for subscription" not "pay per usage". 
If you recalculate this, you will find that there is no comparison in prices

CaptchAI is already available in many Software Captcha options like GSA SER and other third-party library like Captcha-Tools 
So it is an opportunity for any software to add them to service users cause they started taking place in the market recently. 


Anyway, I will send them your opinion
I wish you good luck ^^

**Comment by mdeweerd** [comment]
The offer may certainly start to be interesting if you need more than 25000 captcha resolutions per month or more than 50 every hour for 16 hours every day.
Which is very unlikely to be the case of home users.

**Comment by CaptchaAI** [comment]
Hi @mdeweerd 
We have read all your messages and we got your point.

But If you are still interested in adding us to your Software, We offer **_1 Free Thread for all Your users_**.
All they have to do is :
- Register Using your affiliate link ( You have to create an account  to get your affiliate link)
- Send a Ticket requesting this offer " 1 Free Thread for **MetersToHA** Users"
- Enjoy solve reCAPTCHA 100%, hCaptcha, Solve Media, and 27,500+ image captchas.

Hope that help Your Users ^^

**Comment by mdeweerd** [comment]
I thank you for your proposals and as you know I updated MetersToHA to add captchaai and lost the code during an unfortunate git operation.

The real offer was  1 Free Thread for MetersToHA Users for 1 month " which means that after that MetersToHA users would still have to spend  $180/year which does not meet expections.

Offering a free thread for each user "for life", possibly limited to a limited number of captcha resolutions each day would have been more appropriate knowing that in return you wouild have had the exposure.

I close this issue as a "will not implement again" unless the offer is really adapted to user needs.

**Comment by tikismoke** [comment]
Captchai response is:

Dear,

I believe it's not a lifetime offer, it's available for 1 month.

Sorry for any misunderstanding
😭

**Comment by mdeweerd** [comment]
@tikismoke Thank you for your feedback.  I had asked further clarification but did not get a response yet.

**Comment by mdeweerd** [comment]
CaptchaAI sales indicated that a user can get a free thread by asking every month.
